import deck, player


maindeck = deck.Deck()
maindeck.print_deck()
maindeck.shufflecards()
maindeck.print_deck()
maindeck.set_aside(2)
maindeck.print_deck()
print(maindeck.sideboard)
player1 = player.Player("Player 1")
player2 = player.Player("Player 2")
print(player1)
print(player2)
player1.get_card(maindeck)
player1.print_hand()
player1.get_card(maindeck)
player1.print_hand()
player1.neaten_hand()
player1.print_hand()
player1.get_card(maindeck)
player1.print_hand()
player1.get_card(maindeck)
player1.print_hand()
player1.discard()
player1.print_played()
player1.print_hand()
maindeck.print_deck()