import game

newGame = game.Game(4)
newGame.print_game_status()

# maindeck = deck.Deck()
# maindeck.print_deck()
# maindeck.shufflecards()
# maindeck.print_deck()
# maindeck.set_aside(2)
# maindeck.print_deck()
# maindeck.print_sideboard()
# player1 = player.Player("Player 1")
# player2 = player.Player("Player 2")
# player1.print_player()
# player2.print_player()
# player1.get_card(maindeck)
# player1.print_hand()
# player1.get_card(maindeck)
# player1.print_hand()
# player1.neaten_hand()
# player1.print_hand()
# player1.get_card(maindeck)
# player1.print_hand()
# player1.get_card(maindeck)
# player1.print_hand()
# player1.discard()
# player1.print_played()
# player1.print_hand()
# maindeck.print_deck()
# player1.get_card(maindeck)
# player1.print_hand()
# player1.discard()
# player1.print_played()
# player1.print_player()
# player2.print_player()